### ISSUE TITLE
Demo Website is Erroring

### ISSUE THREAD

**Issue by mwksl** [namecheap/ilc#161]
http://demo.microfrontends.online/news/ is currently returning a 500 error. 

Here's the relevant output in the console:
`common.5ea796b17e7f7fc9ad92.css:1 Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

`noticeError.js:20 {"type":"Error","message":"application 'navbar__at__navbar' died in status LOADING_SOURCE_CODE: Error loading http://demo.microfrontends.online:8235/navbar.js (SystemJS Error#3 https://git.io/JvFET#3)","stack":["Error: application 'navbar__at__navbar' died in status LOADING_SOURCE_CODE: Error loading 
http://demo.microfrontends.online:8235/navbar.js (SystemJS Error#3 https://git.io/JvFET#3)","    at HTMLScriptElement.<anonymous> (http://demo.microfrontends.online/_ilc/client.js:4:5951)"],"additionalInfo":{"type":"FRAGMENT_ERROR","appName":"@portal/navbar","slotName":"navbar","errorId":"bd5591a3-bb36-49cf-8651-f4afb361b0b4"}} Error: application 'navbar__at__navbar' died in status LOADING_SOURCE_CODE: Error loading http://demo.microfrontends.online:8235/navbar.js (SystemJS Error#3 https://git.io/JvFET#3)
    at HTMLScriptElement.<anonymous> (client.js:4)
O @ client.js:90
`

**Comment by oleh-momot** [comment]
Hi @mwksl 
I tried to reproduce your issue but I did not see it
It works for me as expected
Could you check it again?
Thanks!

**Comment by mwksl** [comment]
Looks like it was an issue with our corporate VPN. Surprise, surprise. :)
