### ISSUE TITLE
[Question] Is the nuxt ssr app applicable?

### ISSUE THREAD

**Issue by sdg9670** [namecheap/ilc#180]
Is the nuxt ssr app applicable?

**Comment by StyleT** [comment]
Hi! 
It should be possible to get your Nuxt SSR app running behind ILC. However we don't have any example of it, only [pure Vue.js app with SSR](https://github.com/namecheap/ilc-demo-apps/tree/master/apps/news-ssr). 

To make it work you need your Nuxt app to implement [ILC <-> App Server and Client side interface](https://github.com/namecheap/ilc/blob/master/docs/ilc_app_interface.md).

If you'll have it up and running - pls send us a link, so we could add it to the demo apps.
