### ISSUE TITLE
Demo not working for some reason

### ISSUE THREAD

**Issue by kyoukhana** [namecheap/ilc#185]
I got everything installed no problems with docker but when I visit. 

http://localhost:8233/

I get the following error

```
Oops! Something went wrong. Pls try to refresh page or contact support.
```

This works

http://localhost:4001

**Comment by StyleT** [comment]
Hi! Could you provide exact commands you used to run the demo? As well as more info about your environment (node.js version, OS).

**Comment by kyoukhana** [comment]
I just ran this.  Followed the instructions in quickstart


Run docker-compose up -d

**Comment by StyleT** [comment]
Hi!
Have you ran command from point 3?
"During first launch or shutdown only. Run `docker-compose run registry npm run seed`"

**Comment by kyoukhana** [comment]
This worked I ran this and everything is working ow

```
docker-compose run registry npm run seed

```
