### ISSUE TITLE
Multiples socket hang up and errors 500 related on high traffics [solved via R&D]

### ISSUE THREAD

**Issue by jthibodeauCrakmedia** [namecheap/ilc#444]
Hi,

We are using your app heavily and we have _millions of users_ per month on our website. 
We plugged DataDog agent into the app to analyse some datas to response quick.

We came to a point where we have so much traffic. Socket hang up where throw pretty much randomly on all renderers at differents timestamp.

After digging further more, we found out a correlation between the socket hang up and the SSR timeout from the ILC.

We found a solution.

We wanted to share that to the community. If any others people are stuck to that error.
![image](https://user-images.githubusercontent.com/67754779/184350064-28aa2c95-7fd2-4d98-83de-900ba696b516.png)
The socket hang up that are popping up after the fix.. we suspect there are not correlated with that error.

So, regarding the solution, let say you have all microfrontend SSR timeout to 1000ms, modify the  `freeSocketTimeout` on all agents to less then the 1000ms.

`cfa/ilc/server/tailor/request-fragment.js`
```javascript
const kaAgent = new Agent({ freeSocketTimeout: 750 });
const kaAgentHttps = new HttpsAgent({ freeSocketTimeout: 750 });
```

[Article inspired to solve the issue](https://medium.com/ssense-tech/reduce-networking-errors-in-nodejs-23b4eb9f2d83)
 
Hope somes people get their fix as well! :-)

Regards

**Comment by blackrabbit99** [comment]
@jthibodeauCrakmedia Do not you have standalone test to reproduce this issue ?
