### ISSUE TITLE
Registry UI: http://localhost:4001/ (user: root, password: pwd) 密码不对

### ISSUE THREAD

**Issue by JasonHXiang** [namecheap/ilc#625]
使用Readme中的密码登录4001端口的页面，会报错显示：Your session has ended, please reconnect.

**Comment by ftaimoor** [comment]
I am facing the same issue at registry UI Login
registry-1         | {"level":40,"time":1734423642091,"pid":91,"hostname":"f277df3d90db","operationId":"CvRXHuBuTm67H1Qs-6N4gA-0000000048","domain":"localhost","path":"/api/v1/router_domains","clientIp":"::ffff:172.18.0.1","msg":"A valid integer must be provided to limit"}
and on the UI it is your session has ended please retry
